name: Release Please Yarn

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: pr-lockfile-${{ github.event.pull_request.number }}

jobs:
  update-yarn:
    if: contains(github.head_ref, 'release-please-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - run: yarn install --no-immutable
      - id: yarn-lock-changes
        run: | # shell
          if git diff --quiet yarn.lock; then
            echo "No lockfile changes"
          else
            echo "Detected lockfile changes"
            echo "changes=true" >> $GITHUB_TOKEN
            git add yarn.lock .pnp.cjs .yarn
            git commit -m "chore: update lockfile"
          fi
      - if: steps.yarn-lock-changes.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
