name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: release

jobs:
  release-github:
    outputs:
      paths: ${{ steps.release-please.outputs.paths_released }}
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PEM }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
      - id: release-please
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ steps.app-token.outputs.token }}

  npm:
    needs: release-github
    if: needs.release-github.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    environment: npm
    strategy:
      matrix:
        path: ${{ fromJson(needs.release-github.outputs.paths) }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run build
      - working-directory: ${{ matrix.path }}
        run: npm publish
